
safe: false
pygments: true
markdown: rdiscount
redirects: false
paginate: 10
pagination: true
archive_title_prefix: "Arquivo de "
archive_title_suffix: " "
exclude: ["README.md", "etc/*"]
category_title_prefix: "Tudo em "

scholar:
  style: apa
  locale: en
  sort_by: none
  order: ascending
  source: ./_bibliography
  bibliography: emap.bib
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"  

