
gems:
  - jekyll/scholar
  - jekyll-paginate
  - jekyll-archives
  - jekyll-textile-converter
  - jekyll-email-protect

safe: false
highlighter: rouge
markdown: kramdown
redirects: false
paginate: 10
paginate_path: "/pages/page:num/"
exclude: ["README.md", "etc"]

scholar:
  style: apa
  locale: en
  sort_by: none
  order: ascending
  source: ./_bibliography
  bibliography: emap.bib
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"  

jekyll-archives:
  enabled:
    - categories
    - year
    - tags
  layouts:
    year: archive-year
    category: archive-category
    tag: archive-tag
  permalinks:
    year: '/:year/'
    tag: '/tag/:name/'
    category: '/category/:name/'
    
